apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-store
  template:
    metadata:
      labels:
        app: alert-store
    spec:
      containers:
        - name: alert-store
          image: csborges/alert-store:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/alertsdb
            - name: SPRING_DATASOURCE_USERNAME
              value: alertsuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: alertspassword
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: alert-store
spec:
  ports:
    - port: 8090
  selector:
    app: alert-store
